[package]
name = "companion-for-processbot-staging"
version = "0.1.0"
authors = ["paritytech <info@parity.io>"]
edition = "2018"

[dependencies]
main-for-processbot-staging = { git = "https://github.com/paritytech/main-for-processbot-staging", branch = "master" }
